# vim:noexpandtab:softtabstop=2:tabstop=2:shiftwidth=2:nowrap
#
# License CC0 PUBLIC DOMAIN
#
# To the extent possible under law, Mark J. Olesen has waived all copyright
# and related or neighboring rights to tabitha. This work is published from:
# United States.

DLL=/mingw64/bin
TOP=../..
SRC=${TOP}/src
BIN=bin

GLADE=\
	${BIN}/break.glade\
	${BIN}/README.glade

DEPDLL=\




#	${BIN}/libatk-1.0-0.dll\
#	${BIN}/libbz2-1.dll\
#	${BIN}/libcairo-2.dll\
#	${BIN}/libcairo-gobject-2.dll\
#	${BIN}/libepoxy-0.dll\
#	${BIN}/libexpat-1.dll\
#	${BIN}/libffi-6.dll\
#	${BIN}/libfontconfig-1.dll\
#	${BIN}/libfreetype-6.dll\
#	${BIN}/libgcc_s_seh-1.dll\
#	${BIN}/libgdk_pixbuf-2.0-0.dll\
#	${BIN}/libgdk-3-0.dll\
#	${BIN}/libgio-2.0-0.dll\
#	${BIN}/libglib-2.0-0.dll\
#	${BIN}/libgmodule-2.0-0.dll\
#	${BIN}/libgobject-2.0-0.dll\
#	${BIN}/libgraphite2.dll\
#	${BIN}/libgtk-3-0.dll\
#	${BIN}/libharfbuzz-0.dll\
#	${BIN}/libiconv-2.dll\
#	${BIN}/libicudt57.dll\
#	${BIN}/libicuin57.dll\
#	${BIN}/libicuuc57.dll\
#	${BIN}/libintl-8.dll\
#	${BIN}/libpango-1.0-0.dll\
#	${BIN}/libpangocairo-1.0-0.dll\
#	${BIN}/libpangoft2-1.0-0.dll\
#	${BIN}/libpangowin32-1.0-0.dll\
#	${BIN}/libpcre-1.dll\
#	${BIN}/libpixman-1-0.dll\
#	${BIN}/libpng16-16.dll\
#	${BIN}/libpq.dll\
#	${BIN}/libsqlite3-0.dll\
#	${BIN}/libstdc++-6.dll\
#	${BIN}/libwinpthread-1.dll\
#	${BIN}/mariadb.dll\
#	${BIN}/zlib1.dll

.PHONY: all
all: createdirs

createdirs:
	@test -d ${BIN} || mkdir -p ${BIN}




