# makefile
#
# License CC0 PUBLIC DOMAIN
#
# To the extent possible under law, Mark J. Olesen has waived all copyright
# and related or neighboring rights to tabitha. This work is published from:
# United States.

tabitha-48x48.png : tabitha.svg
	gm convert -scale 48x48 $? $@

